Search.appendIndex(
    [
                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\HmacSigner",
            "name": "HmacSigner",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-HmacSigner.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\HmacSigner\u003A\u003Asign\u0028\u0029",
            "name": "sign",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-HmacSigner.html#method_sign"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\HmacSigner\u003A\u003A\u0024hmacAlg",
            "name": "hmacAlg",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-HmacSigner.html#property_hmacAlg"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha256Signer",
            "name": "Sha256Signer",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha256Signer.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha256Signer\u003A\u003Aalgorithm\u0028\u0029",
            "name": "algorithm",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha256Signer.html#method_algorithm"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha256Signer\u003A\u003A\u0024hmacAlg",
            "name": "hmacAlg",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha256Signer.html#property_hmacAlg"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha384Signer",
            "name": "Sha384Signer",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha384Signer.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha384Signer\u003A\u003Aalgorithm\u0028\u0029",
            "name": "algorithm",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha384Signer.html#method_algorithm"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha384Signer\u003A\u003A\u0024hmacAlg",
            "name": "hmacAlg",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha384Signer.html#property_hmacAlg"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha512Signer",
            "name": "Sha512Signer",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha512Signer.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha512Signer\u003A\u003Aalgorithm\u0028\u0029",
            "name": "algorithm",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha512Signer.html#method_algorithm"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha\\Sha512Signer\u003A\u003A\u0024hmacAlg",
            "name": "hmacAlg",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Hmac-Sha-Sha512Signer.html#property_hmacAlg"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Signer",
            "name": "Signer",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Signer.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Signer\u003A\u003AgetSecret\u0028\u0029",
            "name": "getSecret",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Signer.html#method_getSecret"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Signer\u003A\u003AsetSecret\u0028\u0029",
            "name": "setSecret",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Signer.html#method_setSecret"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Signer\u003A\u003Aalgorithm\u0028\u0029",
            "name": "algorithm",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Signer.html#method_algorithm"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Signer\u003A\u003Asign\u0028\u0029",
            "name": "sign",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Signer.html#method_sign"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Signer\u003A\u003A\u0024secret",
            "name": "secret",
            "summary": "",
            "url": "classes/Corviz-Jwt-Signer-Signer.html#property_secret"
        },                {
            "fqsen": "\\Corviz\\Jwt\\SignerFactory",
            "name": "SignerFactory",
            "summary": "",
            "url": "classes/Corviz-Jwt-SignerFactory.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\SignerFactory\u003A\u003Aassign\u0028\u0029",
            "name": "assign",
            "summary": "",
            "url": "classes/Corviz-Jwt-SignerFactory.html#method_assign"
        },                {
            "fqsen": "\\Corviz\\Jwt\\SignerFactory\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/Corviz-Jwt-SignerFactory.html#method_build"
        },                {
            "fqsen": "\\Corviz\\Jwt\\SignerFactory\u003A\u003A\u0024algMap",
            "name": "algMap",
            "summary": "",
            "url": "classes/Corviz-Jwt-SignerFactory.html#property_algMap"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token",
            "name": "Token",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_create"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AfromAuthorizationBearer\u0028\u0029",
            "name": "fromAuthorizationBearer",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_fromAuthorizationBearer"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AfromQueryString\u0028\u0029",
            "name": "fromQueryString",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_fromQueryString"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AfromString\u0028\u0029",
            "name": "fromString",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_fromString"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AassignValidator\u0028\u0029",
            "name": "assignValidator",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_assignValidator"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AassignHeaderValidator\u0028\u0029",
            "name": "assignHeaderValidator",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_assignHeaderValidator"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_getHeaders"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AgetPayload\u0028\u0029",
            "name": "getPayload",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_getPayload"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AgetLastValidationIssue\u0028\u0029",
            "name": "getLastValidationIssue",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_getLastValidationIssue"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_remove"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AremoveHeader\u0028\u0029",
            "name": "removeHeader",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_removeHeader"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_setHeaders"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AsetPayload\u0028\u0029",
            "name": "setPayload",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_setPayload"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AsetSignature\u0028\u0029",
            "name": "setSignature",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_setSignature"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003Asign\u0028\u0029",
            "name": "sign",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_sign"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_toString"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_validate"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003Awith\u0028\u0029",
            "name": "with",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_with"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_withHeader"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AwithSigner\u0028\u0029",
            "name": "withSigner",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_withSigner"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Corviz-Jwt-Token.html#method___construct"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AgetDefaultSigner\u0028\u0029",
            "name": "getDefaultSigner",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_getDefaultSigner"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AencodeSection\u0028\u0029",
            "name": "encodeSection",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_encodeSection"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003AdecodeSection\u0028\u0029",
            "name": "decodeSection",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#method_decodeSection"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003ADEFAULT_SIGNER",
            "name": "DEFAULT_SIGNER",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#constant_DEFAULT_SIGNER"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_headers"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024lastValidationIssue",
            "name": "lastValidationIssue",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_lastValidationIssue"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024payload",
            "name": "payload",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_payload"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_signature"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024signer",
            "name": "signer",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_signer"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024validators",
            "name": "validators",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_validators"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Token\u003A\u003A\u0024headerValidators",
            "name": "headerValidators",
            "summary": "",
            "url": "classes/Corviz-Jwt-Token.html#property_headerValidators"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\ExpValidator",
            "name": "ExpValidator",
            "summary": "",
            "url": "classes/Corviz-Jwt-Validator-ExpValidator.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\ExpValidator\u003A\u003Avalidates\u0028\u0029",
            "name": "validates",
            "summary": "Must\u0020return\u0020the\u0020validated\u0020field\u0020name\u003B",
            "url": "classes/Corviz-Jwt-Validator-ExpValidator.html#method_validates"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\ExpValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020the\u0020field\u0020specified\u0020by\u0020validates\u0028\u0029.",
            "url": "classes/Corviz-Jwt-Validator-ExpValidator.html#method_validate"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\NbfValidator",
            "name": "NbfValidator",
            "summary": "",
            "url": "classes/Corviz-Jwt-Validator-NbfValidator.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\NbfValidator\u003A\u003Avalidates\u0028\u0029",
            "name": "validates",
            "summary": "Must\u0020return\u0020the\u0020validated\u0020field\u0020name\u003B",
            "url": "classes/Corviz-Jwt-Validator-NbfValidator.html#method_validates"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\NbfValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020the\u0020field\u0020specified\u0020by\u0020validates\u0028\u0029.",
            "url": "classes/Corviz-Jwt-Validator-NbfValidator.html#method_validate"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\Validator",
            "name": "Validator",
            "summary": "",
            "url": "classes/Corviz-Jwt-Validator-Validator.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\Validator\u003A\u003Avalidates\u0028\u0029",
            "name": "validates",
            "summary": "Must\u0020return\u0020the\u0020validated\u0020field\u0020name\u003B",
            "url": "classes/Corviz-Jwt-Validator-Validator.html#method_validates"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator\\Validator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020the\u0020field\u0020specified\u0020by\u0020validates\u0028\u0029.",
            "url": "classes/Corviz-Jwt-Validator-Validator.html#method_validate"
        },                {
            "fqsen": "\\composerRequire747b869a030d971100ab693f1abdebfd\u0028\u0029",
            "name": "composerRequire747b869a030d971100ab693f1abdebfd",
            "summary": "",
            "url": "namespaces/default.html#function_composerRequire747b869a030d971100ab693f1abdebfd"
        },                {
            "fqsen": "\\ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd",
            "name": "ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd.html"
        },                {
            "fqsen": "\\ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd\u003A\u003AloadClassLoader\u0028\u0029",
            "name": "loadClassLoader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd.html#method_loadClassLoader"
        },                {
            "fqsen": "\\ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd\u003A\u003AgetLoader\u0028\u0029",
            "name": "getLoader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd.html#method_getLoader"
        },                {
            "fqsen": "\\ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd\u003A\u003A\u0024loader",
            "name": "loader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit747b869a030d971100ab693f1abdebfd.html#property_loader"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit747b869a030d971100ab693f1abdebfd",
            "name": "ComposerStaticInit747b869a030d971100ab693f1abdebfd",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit747b869a030d971100ab693f1abdebfd.html"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit747b869a030d971100ab693f1abdebfd\u003A\u003AgetInitializer\u0028\u0029",
            "name": "getInitializer",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit747b869a030d971100ab693f1abdebfd.html#method_getInitializer"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit747b869a030d971100ab693f1abdebfd\u003A\u003A\u0024files",
            "name": "files",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit747b869a030d971100ab693f1abdebfd.html#property_files"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit747b869a030d971100ab693f1abdebfd\u003A\u003A\u0024prefixLengthsPsr4",
            "name": "prefixLengthsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit747b869a030d971100ab693f1abdebfd.html#property_prefixLengthsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit747b869a030d971100ab693f1abdebfd\u003A\u003A\u0024prefixDirsPsr4",
            "name": "prefixDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit747b869a030d971100ab693f1abdebfd.html#property_prefixDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit747b869a030d971100ab693f1abdebfd\u003A\u003A\u0024classMap",
            "name": "classMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit747b869a030d971100ab693f1abdebfd.html#property_classMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\includeFile\u0028\u0029",
            "name": "includeFile",
            "summary": "Scope\u0020isolated\u0020include.",
            "url": "namespaces/composer-autoload.html#function_includeFile"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader",
            "name": "ClassLoader",
            "summary": "ClassLoader\u0020implements\u0020a\u0020PSR\u002D0,\u0020PSR\u002D4\u0020and\u0020classmap\u0020class\u0020loader.",
            "url": "classes/Composer-Autoload-ClassLoader.html"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method___construct"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetPrefixes\u0028\u0029",
            "name": "getPrefixes",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getPrefixes"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetPrefixesPsr4\u0028\u0029",
            "name": "getPrefixesPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getPrefixesPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetFallbackDirs\u0028\u0029",
            "name": "getFallbackDirs",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getFallbackDirs"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetFallbackDirsPsr4\u0028\u0029",
            "name": "getFallbackDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getFallbackDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetClassMap\u0028\u0029",
            "name": "getClassMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getClassMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AaddClassMap\u0028\u0029",
            "name": "addClassMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_addClassMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D0\u0020directories\u0020for\u0020a\u0020given\u0020prefix,\u0020either\nappending\u0020or\u0020prepending\u0020to\u0020the\u0020ones\u0020previously\u0020set\u0020for\u0020this\u0020prefix.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_add"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AaddPsr4\u0028\u0029",
            "name": "addPsr4",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D4\u0020directories\u0020for\u0020a\u0020given\u0020namespace,\u0020either\nappending\u0020or\u0020prepending\u0020to\u0020the\u0020ones\u0020previously\u0020set\u0020for\u0020this\u0020namespace.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_addPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D0\u0020directories\u0020for\u0020a\u0020given\u0020prefix,\nreplacing\u0020any\u0020others\u0020previously\u0020set\u0020for\u0020this\u0020prefix.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_set"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetPsr4\u0028\u0029",
            "name": "setPsr4",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D4\u0020directories\u0020for\u0020a\u0020given\u0020namespace,\nreplacing\u0020any\u0020others\u0020previously\u0020set\u0020for\u0020this\u0020namespace.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetUseIncludePath\u0028\u0029",
            "name": "setUseIncludePath",
            "summary": "Turns\u0020on\u0020searching\u0020the\u0020include\u0020path\u0020for\u0020class\u0020files.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setUseIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetUseIncludePath\u0028\u0029",
            "name": "getUseIncludePath",
            "summary": "Can\u0020be\u0020used\u0020to\u0020check\u0020if\u0020the\u0020autoloader\u0020uses\u0020the\u0020include\u0020path\u0020to\u0020check\nfor\u0020classes.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getUseIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetClassMapAuthoritative\u0028\u0029",
            "name": "setClassMapAuthoritative",
            "summary": "Turns\u0020off\u0020searching\u0020the\u0020prefix\u0020and\u0020fallback\u0020directories\u0020for\u0020classes\nthat\u0020have\u0020not\u0020been\u0020registered\u0020with\u0020the\u0020class\u0020map.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setClassMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AisClassMapAuthoritative\u0028\u0029",
            "name": "isClassMapAuthoritative",
            "summary": "Should\u0020class\u0020lookup\u0020fail\u0020if\u0020not\u0020found\u0020in\u0020the\u0020current\u0020class\u0020map\u003F",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_isClassMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetApcuPrefix\u0028\u0029",
            "name": "setApcuPrefix",
            "summary": "APCu\u0020prefix\u0020to\u0020use\u0020to\u0020cache\u0020found\/not\u002Dfound\u0020classes,\u0020if\u0020the\u0020extension\u0020is\u0020enabled.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setApcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetApcuPrefix\u0028\u0029",
            "name": "getApcuPrefix",
            "summary": "The\u0020APCu\u0020prefix\u0020in\u0020use,\u0020or\u0020null\u0020if\u0020APCu\u0020caching\u0020is\u0020not\u0020enabled.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getApcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Registers\u0020this\u0020instance\u0020as\u0020an\u0020autoloader.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_register"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aunregister\u0028\u0029",
            "name": "unregister",
            "summary": "Unregisters\u0020this\u0020instance\u0020as\u0020an\u0020autoloader.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_unregister"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AloadClass\u0028\u0029",
            "name": "loadClass",
            "summary": "Loads\u0020the\u0020given\u0020class\u0020or\u0020interface.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_loadClass"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AfindFile\u0028\u0029",
            "name": "findFile",
            "summary": "Finds\u0020the\u0020path\u0020to\u0020the\u0020file\u0020where\u0020the\u0020class\u0020is\u0020defined.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_findFile"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetRegisteredLoaders\u0028\u0029",
            "name": "getRegisteredLoaders",
            "summary": "Returns\u0020the\u0020currently\u0020registered\u0020loaders\u0020indexed\u0020by\u0020their\u0020corresponding\u0020vendor\u0020directories.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getRegisteredLoaders"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AfindFileWithExtension\u0028\u0029",
            "name": "findFileWithExtension",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_findFileWithExtension"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024vendorDir",
            "name": "vendorDir",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_vendorDir"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024prefixLengthsPsr4",
            "name": "prefixLengthsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_prefixLengthsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024prefixDirsPsr4",
            "name": "prefixDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_prefixDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024fallbackDirsPsr4",
            "name": "fallbackDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_fallbackDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024prefixesPsr0",
            "name": "prefixesPsr0",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_prefixesPsr0"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024fallbackDirsPsr0",
            "name": "fallbackDirsPsr0",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_fallbackDirsPsr0"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024useIncludePath",
            "name": "useIncludePath",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_useIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024classMap",
            "name": "classMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_classMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024classMapAuthoritative",
            "name": "classMapAuthoritative",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_classMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024missingClasses",
            "name": "missingClasses",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_missingClasses"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024apcuPrefix",
            "name": "apcuPrefix",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_apcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A\u0024registeredLoaders",
            "name": "registeredLoaders",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#property_registeredLoaders"
        },                {
            "fqsen": "\\Composer\\InstalledVersions",
            "name": "InstalledVersions",
            "summary": "This\u0020class\u0020is\u0020copied\u0020in\u0020every\u0020Composer\u0020installed\u0020project\u0020and\u0020available\u0020to\u0020all",
            "url": "classes/Composer-InstalledVersions.html"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalledPackages\u0028\u0029",
            "name": "getInstalledPackages",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020all\u0020package\u0020names\u0020which\u0020are\u0020present,\u0020either\u0020by\u0020being\u0020installed,\u0020replaced\u0020or\u0020provided",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalledPackages"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalledPackagesByType\u0028\u0029",
            "name": "getInstalledPackagesByType",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020all\u0020package\u0020names\u0020with\u0020a\u0020specific\u0020type\u0020e.g.\u0020\u0027library\u0027",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalledPackagesByType"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AisInstalled\u0028\u0029",
            "name": "isInstalled",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020package\u0020is\u0020installed",
            "url": "classes/Composer-InstalledVersions.html#method_isInstalled"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003Asatisfies\u0028\u0029",
            "name": "satisfies",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020package\u0020satisfies\u0020a\u0020version\u0020constraint",
            "url": "classes/Composer-InstalledVersions.html#method_satisfies"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetVersionRanges\u0028\u0029",
            "name": "getVersionRanges",
            "summary": "Returns\u0020a\u0020version\u0020constraint\u0020representing\u0020all\u0020the\u0020range\u0028s\u0029\u0020which\u0020are\u0020installed\u0020for\u0020a\u0020given\u0020package",
            "url": "classes/Composer-InstalledVersions.html#method_getVersionRanges"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getVersion"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetPrettyVersion\u0028\u0029",
            "name": "getPrettyVersion",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getPrettyVersion"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetReference\u0028\u0029",
            "name": "getReference",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getReference"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstallPath\u0028\u0029",
            "name": "getInstallPath",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getInstallPath"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetRootPackage\u0028\u0029",
            "name": "getRootPackage",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getRootPackage"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetRawData\u0028\u0029",
            "name": "getRawData",
            "summary": "Returns\u0020the\u0020raw\u0020installed.php\u0020data\u0020for\u0020custom\u0020implementations",
            "url": "classes/Composer-InstalledVersions.html#method_getRawData"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetAllRawData\u0028\u0029",
            "name": "getAllRawData",
            "summary": "Returns\u0020the\u0020raw\u0020data\u0020of\u0020all\u0020installed.php\u0020which\u0020are\u0020currently\u0020loaded\u0020for\u0020custom\u0020implementations",
            "url": "classes/Composer-InstalledVersions.html#method_getAllRawData"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003Areload\u0028\u0029",
            "name": "reload",
            "summary": "Lets\u0020you\u0020reload\u0020the\u0020static\u0020array\u0020from\u0020another\u0020file",
            "url": "classes/Composer-InstalledVersions.html#method_reload"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalled\u0028\u0029",
            "name": "getInstalled",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalled"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003A\u0024installed",
            "name": "installed",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#property_installed"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003A\u0024canGetVendors",
            "name": "canGetVendors",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#property_canGetVendors"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003A\u0024installedByVendor",
            "name": "installedByVendor",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#property_installedByVendor"
        },                {
            "fqsen": "\\getallheaders\u0028\u0029",
            "name": "getallheaders",
            "summary": "Get\u0020all\u0020HTTP\u0020header\u0020key\/values\u0020as\u0020an\u0020associative\u0020array\u0020for\u0020the\u0020current\u0020request.",
            "url": "namespaces/default.html#function_getallheaders"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac",
            "name": "Hmac",
            "summary": "",
            "url": "namespaces/corviz-jwt-signer-hmac.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer\\Hmac\\Sha",
            "name": "Sha",
            "summary": "",
            "url": "namespaces/corviz-jwt-signer-hmac-sha.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Signer",
            "name": "Signer",
            "summary": "",
            "url": "namespaces/corviz-jwt-signer.html"
        },                {
            "fqsen": "\\Corviz\\Jwt",
            "name": "Jwt",
            "summary": "",
            "url": "namespaces/corviz-jwt.html"
        },                {
            "fqsen": "\\Corviz",
            "name": "Corviz",
            "summary": "",
            "url": "namespaces/corviz.html"
        },                {
            "fqsen": "\\Corviz\\Jwt\\Validator",
            "name": "Validator",
            "summary": "",
            "url": "namespaces/corviz-jwt-validator.html"
        },                {
            "fqsen": "\\Composer\\Autoload",
            "name": "Autoload",
            "summary": "",
            "url": "namespaces/composer-autoload.html"
        },                {
            "fqsen": "\\Composer",
            "name": "Composer",
            "summary": "",
            "url": "namespaces/composer.html"
        }            ]
);
